import Link from 'next/link';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';

export const metadata = {
  title: 'Terms of Service — InstaOffer',
  description: 'Terms and conditions for using the InstaOffer platform in Qatar.',
};

export default function TermsPage() {
  return (
    <div className="flex flex-col min-h-screen bg-[#f5f7fa]">
      <Navbar />
      <main className="flex-1 max-w-3xl mx-auto px-4 py-12 w-full">
        <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-8 md:p-12">
          <Link href="/" className="text-sm text-[#003087] hover:underline mb-6 inline-block">
            ← Back to home
          </Link>

          <h1 className="text-3xl font-black text-gray-900 mb-2">Terms of Service</h1>
          <p className="text-sm text-gray-400 mb-8">Last updated: April 2026</p>

          <div className="prose prose-gray max-w-none space-y-8 text-gray-700 leading-relaxed">

            <section>
              <h2 className="text-xl font-bold text-gray-900 mb-3">1. Acceptance of terms</h2>
              <p>
                By accessing or using InstaOffer, you agree to be bound by these Terms of Service. If you
                do not agree, please do not use the platform.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-gray-900 mb-3">2. Platform description</h2>
              <p>
                InstaOffer is an online marketplace that provides AI-powered vehicle valuations and
                connects car sellers in Qatar with licensed dealers. We are a platform intermediary and
                are not a party to any transaction between sellers and dealers.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-gray-900 mb-3">3. Seller obligations</h2>
              <ul className="list-disc pl-5 space-y-2">
                <li>You must be the legal owner of the vehicle or authorised to sell it.</li>
                <li>All information you provide must be accurate and not misleading.</li>
                <li>Uploaded documents (registration, inspection reports) must be genuine.</li>
                <li>You are responsible for any final sale transaction, which occurs outside the platform.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-bold text-gray-900 mb-3">4. Dealer obligations</h2>
              <ul className="list-disc pl-5 space-y-2">
                <li>Dealers must hold a valid Qatar commercial licence for car trading.</li>
                <li>Dealers agree to pay the monthly subscription fee of 1,000 QAR.</li>
                <li>Dealers may not contact sellers through means other than those provided by the platform without explicit seller approval.</li>
                <li>Dealers must not misrepresent their identity or offer terms.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-bold text-gray-900 mb-3">5. Non-binding offers</h2>
              <p>
                All offers submitted through InstaOffer are <strong>non-binding</strong> and subject to
                physical vehicle inspection. Neither the seller nor the dealer is legally obligated to
                complete a transaction based on an offer made through the platform.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-gray-900 mb-3">6. Valuation accuracy</h2>
              <p>
                Instant valuations are generated by a machine-learning model trained on Qatar market data.
                They are estimates only and may not reflect the actual sale price. InstaOffer makes no
                warranty as to the accuracy of any valuation.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-gray-900 mb-3">7. Phone number sharing</h2>
              <p>
                Sellers must explicitly approve any dealer request to access their phone number. InstaOffer
                logs all approvals. Dealers who misuse contact information will be suspended.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-gray-900 mb-3">8. Prohibited conduct</h2>
              <ul className="list-disc pl-5 space-y-2">
                <li>Posting fraudulent or fictitious vehicle listings.</li>
                <li>Attempting to contact sellers outside the platform without approval.</li>
                <li>Manipulating the valuation system or bidding process.</li>
                <li>Scraping or automating access to the platform.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-bold text-gray-900 mb-3">9. Termination</h2>
              <p>
                InstaOffer reserves the right to suspend or terminate any account that violates these terms,
                without prior notice.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-gray-900 mb-3">10. Limitation of liability</h2>
              <p>
                InstaOffer is not liable for any loss arising from reliance on valuations, failed
                transactions, or disputes between sellers and dealers. Use the platform at your own risk.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-gray-900 mb-3">11. Governing law</h2>
              <p>
                These terms are governed by the laws of the State of Qatar. Any disputes shall be subject
                to the jurisdiction of Qatari courts.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-gray-900 mb-3">12. Contact</h2>
              <p>
                For questions about these terms:{' '}
                <a href="mailto:legal@instaoffer.qa" className="text-[#003087] hover:underline">
                  legal@instaoffer.qa
                </a>
              </p>
            </section>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
}
