// ─── WhatsApp contact number ──────────────────────────────────────────────────
// Support line in wa.me format (digits only, no '+'). Configurable per
// environment via NEXT_PUBLIC_SUPPORT_WHATSAPP; falls back to the known business
// line (+974 5204 6176). Set the env var to an empty string to hide WhatsApp UI.
export const WA_NUMBER = (process.env.NEXT_PUBLIC_SUPPORT_WHATSAPP ?? '97452046176').replace(/\D/g, '');

/** Whether a support WhatsApp number is configured — callers hide the UI if not. */
export const WHATSAPP_ENABLED = WA_NUMBER.length > 0;

/** Build a wa.me URL with an optional pre-filled message, or '' when unconfigured. */
export function waLink(message = ''): string {
  if (!WA_NUMBER) return '';
  return `https://wa.me/${WA_NUMBER}${message ? `?text=${encodeURIComponent(message)}` : ''}`;
}

export function formatQAR(amount: number): string {
  return `QAR ${amount.toLocaleString('en-QA')}`;
}

export function formatKM(km: number): string {
  return `${km.toLocaleString('en-QA')} km`;
}

// Unambiguous, localized date: "12 Jun 2026" (en) or the Arabic equivalent.
// The month is always spelled out so it can't be misread as DD/MM vs MM/DD.
// Locale defaults to whatever the LocaleProvider set on <html lang> so every
// call site localizes automatically; pass an explicit locale to override.
export function formatDate(iso: string, locale?: string): string {
  const lang = locale
    || (typeof document !== 'undefined' ? document.documentElement.lang : '')
    || 'en';
  const loc = lang.startsWith('ar') ? 'ar' : 'en-QA';
  return new Date(iso).toLocaleDateString(loc, {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
  });
}

export function clamp(value: number, min: number, max: number): number {
  return Math.max(min, Math.min(max, value));
}

export const CAR_MAKES = [
  "Toyota",
  "Nissan",
  "Lexus",
  "Land Rover",
  "Mercedes-Benz",
  "BMW",
  "Chevrolet",
  "Mitsubishi",
  "Ford",
  "GMC",
  "Jetour",
  "Kia",
  "Honda",
  "Porsche",
  "Jeep",
  "Hyundai",
  "Audi",
  "Dodge",
  "Volkswagen",
  "Suzuki",
  "MG",
  "GWM",
  "Geely",
  "BYD",
  "Chery",
  "Infiniti",
  "Cadillac",
  "Mazda",
  "Renault",
  "GAC",
  "Bentley",
  "Tesla",
  "Changan",
  "Haval",
  "Genesis",
  "Fiat",
  "Jaguar",
  "Maserati",
  "Rolls-Royce",
  "Rox Motor",
  "Volvo",
  "Bestune",
  "Subaru",
  "Peugeot",
  "Lamborghini",
  "Hongqi",
  "Exeed",
  "Alfa Romeo",
  "AERO",
  "AITO",
  "AK",
  "Acura",
  "Ankai",
  "Ariel",
  "Ashok",
  "Aston Martin",
  "Austin Healey",
  "Avatr",
  "BAW",
  "Baic",
  "Baojun",
  "Borgward",
  "Bugatti",
  "Buggy",
  "Buick",
  "CMC",
  "Chrysler",
  "Citroen",
  "Clup Car",
  "DFSK",
  "Daihatsu",
  "Dallara",
  "Datsun",
  "De Tomaso",
  "Domy",
  "Dong Sing",
  "Dongfeng",
  "FUSO",
  "Factory Five",
  "Fang Cheng",
  "Ferrari",
  "Fisker",
  "Force",
  "Forthing",
  "Foton",
  "Fun Car",
  "Great Wall",
  "Haima",
  "Higer",
  "Hino",
  "Hongsheng",
  "Huanghai",
  "Hummer",
  "Imperial",
  "Ineos",
  "International",
  "Isuzu",
  "Iveco",
  "JAC Motors",
  "JBC",
  "JMC",
  "Jaecoo",
  "Jensen",
  "Jinbei",
  "KTM",
  "Kaiyi",
  "King Long",
  "Koenigsegg",
  "LYKAN",
  "Lada",
  "Lancia",
  "Leapmotor",
  "Ligier",
  "Lincoln",
  "Local Motors",
  "Lotus",
  "Lynk & Co",
  "M Hero",
  "MACK",
  "Mahindra",
  "Mangosta",
  "Maxus",
  "Maybach",
  "Mclaren",
  "Mercury",
  "Mini",
  "Mini Mark",
  "Mitsuoka",
  "Morgan",
  "Noble Automotive",
  "Oldsmobile",
  "Omoda",
  "Opel",
  "Pagani",
  "Panoz",
  "Plymouth",
  "Polaris",
  "Polestar",
  "Pontiac",
  "Proton",
  "Radical",
  "Rally Fighter",
  "Rariro",
  "Rely",
  "Rivian",
  "SSangyong",
  "SWM",
  "Saab",
  "Saturn",
  "Scania",
  "Seat",
  "Skoda",
  "Smart",
  "Soueast",
  "Studebaker",
  "TAM",
  "TATA",
  "TVR",
  "Taxi london",
  "Today Sunshine",
  "Triumph",
  "Vanderhall",
  "Voyah",
  "Wiseman",
  "Wuling",
  "XPeng",
  "Xiaomi",
  "Yamaha",
  "YoYo",
  "Zeekr",
  "Zheng Zhou",
  "Zhongxing",
  "Zimmer",
  "Zotye",
  "Zotye Domy",
  "Zxauto",
  "daewoo",
  "lucid"
];

export const CAR_MODELS: Record<string, string[]> = {
  "Toyota": ["4Runner", "Alphard", "Aurion", "Avalon", "Avanza", "BZ4X", "C-HR", "Camry", "Celica", "CENTURY", "Coaster", "Corolla", "Cressida", "Crown", "DYNA", "ECHO", "FJ Cruiser", "Fortuner", "FT 86", "GR 86", "Granvia", "GT 86", "Hiace", "Highlander", "Hilux", "Innova", "IQ", "Land Cruiser", "Levin", "Lite Ace", "Matrix", "MR2", "Prado", "Previa", "Prius", "Raize", "Rav 4", "Rush", "Scion", "Sequoia", "Sienna", "Solara", "Sunshine", "Supra", "Tacoma", "Tercel", "Tundra", "Urban Cruiser", "Veloz", "Venza", "XA", "Yaris", "Zelas"],
  "Nissan": ["280 ZX", "300 ZX", "Altima", "Ariya", "Armada", "Cedric", "Civilian", "GT-R", "Juke", "Kicks", "Magnite", "Maxima", "Micra", "Murano", "MV 350", "Navara", "Pathfinder", "Patrol", "Pickup", "Qashqai", "Quest", "Rogue", "Sentra", "Silvia", "Skyline", "Sunny", "Tiida", "Titan", "Urvan", "Van", "X-Trail", "Xterra", "Z"],
  "Lexus": ["CT", "ES", "GS", "GX", "IQ", "IS", "LC", "LFA", "LM", "LS", "LX", "NX", "RC", "RM2", "RX", "SC", "UX"],
  "Land Rover": ["Defender", "Discovery", "Evoque", "Freelander", "LR2", "LR3", "LR4", "Minerva", "Range Rover"],
  "Mercedes-Benz": ["250 CE", "250 S", "250 SE", "280 SE", "280 SEL", "300 CE", "300 SE", "380 S", "380 SEL", "380 SL", "450 SEL", "450 SL", "450 SLC", "500 SEL", "500 SLE", "560 SEL", "560 SL", "A-Class", "Atego", "B-Class", "C-Class", "CL", "CLA", "Classic", "CLC", "CLE", "CLK", "CLS", "E-Class", "EQA", "EQB", "EQC", "EQE", "EQS", "G-Class", "GE", "GL", "GLA", "GLB", "GLC", "GLE", "GLK", "GLS", "GT", "GT", "LP", "Maybach", "ML", "R-Class", "R107", "Roadster", "S-Class", "SE 260", "SL", "SLC", "SLK", "SLR", "SLS", "Smart", "Sprinter", "Unimog", "V-Class", "Viano", "Vito", "X-Class", "Zetros"],
  "BMW": ["1-Series", "2-Series", "2002", "3-Series", "4-Series", "5-Series", "6-Series", "7-Series", "8-Series", "Alpina", "I-Series", "IX", "M-Series", "X-Series", "XM", "Z-Series"],
  "Chevrolet": ["454", "Apache", "Avalanche", "Aveo", "Bel air", "Bel Air", "Blazer", "BUS", "C10/K10", "Camaro", "Caprice", "Captiva", "Chevelle", "Cheyenne", "Classic", "Cobalt", "Colorado", "corvair", "Corvette", "Cruze", "Delray", "El camino", "Entervan", "Epica", "Equinox", "Express", "Groove", "HHR", "Holden", "Impala", "Kodiak", "Lumina", "Malibu", "Monte Carlo", "Optra", "Pickup", "Savana", "Silverado", "Sonic", "Spark", "SS", "SSR", "Suburban", "Tahoe", "TrailBlazer", "Traverse", "Trax", "Uplander", "Van", "Z25 Grand"],
  "Mitsubishi": ["ASX", "Attrage", "Eclipse", "Fuso Canter", "Galant", "Grandis", "L 200", "L300", "Lancer", "Magna", "Mirage", "Nativa", "Outlander", "Pajero", "Pickup", "Rose", "Van", "XForce", "Xpander"],
  "Ford": ["500", "Bronco", "Classic", "Cobra", "Crown Victoria", "Custom Cab", "Customline", "Daytona", "E", "Eco Sport", "Edge", "EDSEL", "Escape", "Escort", "Everest", "Everest", "Excursion", "Expedition", "Explorer", "F", "Fiesta", "Figo", "Five Hundred", "FLEX", "Focus", "Freestar", "Fusion", "Galaxy 500", "Grand Marquis", "GT", "GTX", "Hennessey", "Kuga", "Mach-E GT Performance", "Mercury", "Milan", "Mondeo", "Mustang", "Pickup", "Ranger", "Raptor", "Shelby", "Super Duty", "Taurus", "Territory", "Thunderbird", "Transit", "Van", "Zimmer"],
  "GMC": ["Acadia", "C 100", "C6500", "C7500", "Canyon", "Classic", "Denali NY", "Envoy", "Hummer EV", "Jimmy", "Pickup", "Savana", "Sierra", "Sonoma", "Suburban", "Syclone", "Terrain", "Van", "Yukon"],
  "Jetour": ["Dashing", "G700", "T1", "T2", "X50", "X70", "X90"],
  "Kia": ["4000", "Cadenza", "Carens", "Carnival", "Cerato", "EV", "Grand Carnival", "K5", "K8", "K900", "Kx1", "Mohave", "Opirus", "Optima", "Pegas", "Picanto", "Pickup", "PREGIO", "Quoris", "Retona", "Rio", "Seltos", "Shuma", "Sonet", "Sorento", "Soul", "Sportage", "Stinger", "Tasman", "Telluride"],
  "Honda": ["Accord", "City", "Civic", "Crosstour", "CRV", "CRX", "CRZ", "Delsol", "Element", "HRV", "JAZZ", "Legend", "MRV", "NSX", "Odyssey", "Pilot", "Prelude", "Ridgeline", "S2000", "SRZ", "Stream", "ZR-V"],
  "Porsche": ["356", "718", "911", "918", "935", "944", "991", "997", "Boxster", "Cayenne", "Cayman", "Gemballa", "Macan", "Panamera", "Slant Nose", "Targa", "Targa", "Taycan"],
  "Jeep": ["Cherokee", "Cj 7", "Commander", "Compass", "Gladiator", "Grand Cherokee", "Grand Wagoneer", "Laredo", "Liberty", "Patriot", "Renegade", "Wagoneer", "Willys", "Wrangler"],
  "Hyundai": ["Accent", "Atoz", "Avante", "Azera", "Centennial", "County", "Coupe FX", "Creta", "DH65", "Elantra", "Galloper", "Genesis", "Getz", "Grand Creta", "Grand Santa Fe", "HD 78", "HD65", "HD72", "I", "Ioniq", "ix", "Kona", "Matrix", "Palisade", "Pickup", "Santa Fe", "Sonata", "Staria", "Terracan", "Trajet", "Tucson", "Universe Space", "Van H1", "Veloster", "Venue", "Veracruz"],
  "Audi": ["A1", "A3", "A4", "A5", "A6", "A7", "A8", "AS8", "Avant RS4", "E-Tron", "IS8", "Q2", "Q3", "Q4", "Q5", "Q6", "Q7", "Q8", "R8", "RS", "RSQ8", "RSS", "S", "SQ5", "SQ8", "TT"],
  "Dodge": ["440", "Avenger", "Caliber", "Challenger", "Charger", "Classic", "D100", "D200", "Durango", "Intrepid", "Journey", "Magnum", "Neon", "Nitro", "Pickup", "Plymouth", "Power Wagon", "Ram", "Super Bee", "Van", "Viper"],
  "Volkswagen": ["Amarok", "Arteon", "Beetle", "Caddy", "Caravelle", "CC", "Crafter", "Eos", "Eos", "Golf", "Grand California", "ID", "Jetta", "Kombi", "MG", "Multivan", "Passat", "Phaeton", "Polo", "R-Line", "R32", "R36", "Revo", "Routan", "Scirocco", "Short Bus", "T-Roc", "Teramont", "Tiguan", "Touareg", "Transporter", "Van", "volkswagen"],
  "Suzuki": ["Alto", "APV", "Baleno", "Carry", "Celerio", "Ciaz", "Dzire", "Ertiga", "Fronx", "Grand Vitara", "Ignis", "Jimny", "K10", "KIZASHI", "KTM", "Liana", "LJ", "LX500", "Pickup", "Samurai", "SG 410", "Swift", "SX4", "Vitara", "X90", "XL 7"],
  "MG": ["3", "350 C", "350 S", "360", "5", "550 S", "7", "75", "750 E", "GS", "GT", "HS", "Kit Car", "MG5", "MG6", "One", "Roadster", "RX", "RX5", "RX8", "RX9", "S 50", "Whale", "Zs", "ZsT", "Standard"],
  "GWM": ["ORA 03", "POER", "Tank"],
  "Geely": ["Azkarra", "Binray", "Cityray", "Coolray", "Emgrand", "GX 3", "Monjaro", "Okavango", "Radar Rd 5", "Starray", "Tugella"],
  "BYD": ["5", "ATTO 3", "Denza", "Han 3.95", "Leopard 3", "Leopard 5", "Leopard 7", "Leopard 8", "Qin Plus", "Seagull", "Seal", "Sealion", "Shark", "Song L", "Tang", "yang Wang", "Yuagwang"],
  "Chery": ["A520", "Arrizo 3", "Arrizo 5", "Arrizo 6", "Arrizo 8", "Chery", "E5", "Himava", "iCAR", "Omoda", "Oriente", "P5", "Tiggo"],
  "Infiniti": ["EX", "FX", "G", "JX", "M", "Q", "QX"],
  "Cadillac": ["ATS", "ATS-V", "BLS", "Brougham", "Classic", "Concours", "CT4", "CT5", "CT6", "CTS", "DeVille", "DTS", "Eldorado", "Escalade", "Fleetwood", "Lyriq", "Optiq", "SLS", "SRX", "STS", "Vistiq", "XLR", "XT4", "XT5", "XT6", "XTS"],
  "Mazda": ["323", "BT-50", "CX", "E2000", "L2000", "Mazda 2", "Mazda 3", "Mazda 6", "Mazda Speed", "Miata", "MPV", "MX", "Pickup", "RX"],
  "Renault": ["10", "Arkana", "Capture", "City", "Clio", "Dokker", "Duster", "Espace", "Express", "Fluence", "Koleos", "Logan", "Megane", "Safrane", "Scenic", "Symbol", "Talisman", "Trafic Van", "Twizy", "Velsatis"],
  "GAC": ["Aion", "Emkoo", "Empow", "Emzoom", "G55", "GA 3S", "GA 4", "GA 5", "GA6", "GA8", "GC4", "GN", "GN6", "GS 3", "GS 4", "GS 5", "GS 7", "GS 8", "M8", "TRUMPCHI"],
  "Bentley": ["Arnage", "Azure", "Batur", "Bentayga", "Brooklands", "Concours", "Continental", "Eight", "GT", "GTC", "Mansory", "Mulsanne"],
  "Tesla": ["85", "CyberBeast", "Cybertruck", "Model 3", "Model S", "Model X", "Model Y", "Roadster"],
  "Changan": ["Alsvin", "CS", "Deepal", "Eado", "Hunter", "UN", "UNI-K", "UNI-S", "UNI-T", "UNI-V"],
  "Haval": ["H6", "H7", "H9", "HI 4", "Jolion", "V7"],
  "Genesis": ["5.0", "G70", "G80", "G90", "GV 60", "GV 70", "GV 80"],
  "Fiat": ["124", "2000", "500", "595", "695", "Bravo", "C 500", "C 600", "Coupe", "Doblo", "Ducato", "Fiorino", "Linea", "Punto", "Tipo", "Tipo"],
  "Jaguar": ["Classic", "Daimler", "E-Pace", "F-Pace", "F-Type", "F-Type R", "I-Pace", "Portfolio", "S-Type", "S-Type R", "Sovereign", "TBS", "v", "X-Type", "XE", "XF", "XJ", "XJL", "XK", "XKR"],
  "Maserati": ["Cambiocorsa", "Ghibli", "Grancabrio", "GranSport", "GranTurismo", "Grecale", "Levante", "MC 20", "MC Stradale", "Quattroporte", "Quattroporte Granlusso"],
  "Rolls-Royce": ["Classic", "Corniche", "Cullinan", "Dawn", "Ghost", "Mansory", "Phantom", "Pininfarina", "Silver Cloud", "Silver Dawn", "Silver Seraph", "Silver Shadow", "Silver Spirit", "Silver Spur", "Silver Wraith II", "Spectre", "Wraith"],
  "Rox Motor": ["Jishi"],
  "Volvo": ["262 coupe", "C30", "C60", "C70", "EX", "S", "V", "XC"],
  "Bestune": ["B70", "T 90", "T33", "T77", "T99"],
  "Subaru": ["BRZ", "Crosstrek", "Forester", "Impreza", "Legacy", "Outback", "STI", "Tribeca", "WRX", "XV"],
  "Peugeot": ["2008", "201", "206", "207", "208", "3008", "301", "307", "308", "404", "407", "408", "5008", "504", "508", "607", "Boxer", "Expert", "Landtrek", "Partner", "RCZ", "Rifter", "Traveller"],
  "Lamborghini": ["Aventador", "Countach", "Diablo", "Gallardo", "Huracan", "LM002", "Murcielago", "Revuelto", "Sian", "Superleggera", "Urus"],
  "Hongqi": ["E-HS9", "H5", "H9", "HS3", "HS5", "HS7", "Ousado"],
  "Exeed": ["Exlantis", "LX", "RX", "TXL", "VX"],
  "Alfa Romeo": ["147", "159", "166", "4 C", "Brera", "Giulia", "Giulietta", "Spider", "Stelvio"],
  "AITO": ["M5", "M7", "M8", "M9"],
  "AK": ["HK6700K"],
  "Acura": ["NSX"],
  "Ankai": ["A6"],
  "Ariel": ["Nomad"],
  "Ashok": ["Leyland"],
  "Aston Martin": ["3000 MK", "Cygnet", "DB", "Healy", "Mirage", "One 77", "Rapide", "Speedster", "Vanquish", "Vantage", "Virage"],
  "Austin Healey": ["3000 MKIII", "Classic"],
  "Avatr": ["011", "06", "07", "11", "12"],
  "BAW": ["212", "Brumby", "EV MPV", "EV Small Truck", "MPV", "MPv M7", "Pick- Up", "Pony", "Small Truck"],
  "Baic": ["A 115", "BJ30", "BJ30e", "BJ40 C", "BJ40 PRO", "BJ60", "BJ80", "D20", "Senova", "U5 Plus", "X35", "X65", "X7"],
  "Baojun": ["Yep", "Yep"],
  "Borgward": ["BX", "Isabelia"],
  "Bugatti": ["Chiron", "Classic", "Divo", "Veyron"],
  "Buggy": ["450", "ARCTIC CAT", "Buckshot", "Can-am", "Cobra 320", "Fighter", "Hayabusa", "Jeep", "Kawasaki", "M/C", "RED LINE", "Sand Limo", "Sand Works", "Suzuki", "T-REX", "TGO", "TukTuk", "XY"],
  "Buick": ["8", "Classic", "Electra", "GSX", "Lesabre", "Park Avenue", "Riviera", "Roadmaster", "Skylark", "Special S", "Sport", "Super"],
  "CMC": ["CMC", "D270", "Veryca"],
  "Chrysler": ["200C", "300 S", "300C", "300M", "Classic", "Concorde", "Crossfire", "Grand Voyager", "Imperial", "LHS", "Neon", "Pacifica", "Prowler", "PT-Cruzar", "Sebring", "Town Country"],
  "Citroen": ["Berlingo", "C-  elysee", "C-3", "C-4", "C-5", "DS 3", "DS 4", "EX", "Jumper", "Xantia", "Xsara"],
  "Clup Car": ["Golf"],
  "DFSK": ["E5", "Glory"],
  "Daihatsu": ["Copen", "Delta", "Extol", "Gran Max", "Rocky", "Sirion", "Terios"],
  "Dallara": ["F3"],
  "Datsun": ["280", "B 120", "Fairlady", "Pick up", "Z 60"],
  "De Tomaso": ["Guar\u00e0"],
  "Domy": ["X7"],
  "Dong Sing": ["Pick up"],
  "Dongfeng": ["007", "A 08", "A30", "A60 Max", "AX7 Mach", "Box", "Captain - C", "Captain - E", "E 70", "Friday", "Huge", "Mage", "P9", "S50", "Shine", "T5", "Utour M4"],
  "FUSO": ["Canter"],
  "Factory Five": ["Hot Road"],
  "Fang Cheng": ["Leopard 5"],
  "Ferrari": ["12Cilindri", "208", "296", "308 GTB", "328", "355", "360 Spider", "458", "488", "512", "575", "599", "612 Scaglietti", "812", "California", "California F1", "Enzo", "F12", "F12 Berlinetta", "F12 Novitec", "F12 TDF", "F2001 Formula 1", "F350", "F360", "F430", "F450", "F8", "F8 Tributo", "FF", "GT", "GTB", "GTC4lusso", "GTO", "La Ferrari", "Lusso", "Mondial", "Portofino", "Purosangue", "Roma", "scuderia", "SF90 Spider", "SF90 Stradale"],
  "Fisker": ["Karma"],
  "Force": ["Traveller"],
  "Forthing": ["T5"],
  "Foton": ["AUV", "Bus", "Pick up", "Sauvana", "Van", "View"],
  "Fun Car": ["Fun Car"],
  "Great Wall": ["Diesel", "Elite", "Hover", "Pickup", "Pilot", "Poer", "proteus", "Safe", "Wingle 5", "Wingle 6", "Wingle 7"],
  "Haima": ["3"],
  "Higer": ["Bus"],
  "Hino": ["300"],
  "Hongsheng": ["Standard"],
  "Huanghai": ["Pickup N2"],
  "Hummer": ["H1", "H2", "H3", "T H2"],
  "Imperial": ["Crown"],
  "Ineos": ["Grenadier"],
  "International": ["4900", "Bus", "MXT"],
  "Isuzu": ["Bus", "D-Max", "ELF", "MU-X", "NMR", "NPR", "Pickup", "Reward", "Trooper", "Viacros"],
  "Iveco": ["Soc15", "Van"],
  "JAC Motors": ["GA8", "GS3", "GS8", "GS8", "J7", "Jac", "JS3", "JS4", "JS6", "M4", "Shuailing", "Sunray", "T6", "T8"],
  "JBC": ["Pick Up"],
  "JMC": ["Pickup"],
  "Jaecoo": ["J5", "J7", "J8"],
  "Jensen": ["Interceptor"],
  "Jinbei": ["Haise", "JBC"],
  "KTM": ["X-Bow / GT"],
  "Kaiyi": ["X3", "X7"],
  "King Long": ["Mini Bus", "MQ-6858", "Van"],
  "Koenigsegg": ["Agera R", "CCX", "CCXR", "Jesko Attack", "Regera"],
  "LYKAN": ["Hypersport"],
  "Lada": ["Niva", "Urban"],
  "Lancia": ["Spider", "Thesis"],
  "Leapmotor": ["C01", "C11", "C11 Reev", "S01", "T03"],
  "Ligier": ["Ligier"],
  "Lincoln": ["05", "09", "Aviator", "Classic", "Continental", "Corsair", "Mark", "MKC", "MKS", "MKT", "MKX", "MKZ", "Nautilus", "Navigator", "Town Car"],
  "Local Motors": ["Rally Fighter"],
  "Lotus": ["3-ELEVEN", "Eletre", "Elise sc", "Emeya", "Emira", "Esprit", "Evora", "Exige", "Exige S", "Hennessey Venom GT"],
  "Lynk & Co": ["01", "03", "05", "06", "09", "900"],
  "M Hero": ["917", "M817", "One"],
  "MACK": ["MACK"],
  "Mahindra": ["Pick Up", "XUV 500"],
  "Mangosta": ["Q nale"],
  "Maxus": ["C 300", "D 90", "D60", "DELIVER 9", "G10", "G50", "G90", "T60", "T70", "T90", "V80"],
  "Maybach": ["Type 57", "Type 62"],
  "Mclaren": ["12-C Spider", "540", "560 S", "570", "600", "650 S", "675 LT", "720", "730 S", "750", "765 LT", "Artura", "Elva", "GT", "MP4", "MP4- 12C", "P1", "Senna"],
  "Mercury": ["CLONY PARK", "Grand Marquis", "Marquis", "Milan", "Montego", "Mountaineer"],
  "Mini": ["Cooper", "Rover"],
  "Mini Mark": ["Mini Mark"],
  "Mitsuoka": ["Galue", "Himiko", "MX-5", "Orochi"],
  "Morgan": ["AERO", "Plus 4"],
  "Noble Automotive": ["M"],
  "Oldsmobile": ["Classic"],
  "Omoda": ["230T", "5", "C5", "S5"],
  "Opel": ["GT", "Omega"],
  "Pagani": ["Huayra"],
  "Panoz": ["Esperante"],
  "Plymouth": ["Belvedere", "P8", "Prowler", "Sport Fury", "Valiant"],
  "Polaris": ["170 CC", "70 CC", "RZ-R", "SDR", "SlingShot"],
  "Polestar": ["2"],
  "Pontiac": ["Buick", "Chiftain", "Classic", "Fiero", "Firebird", "Firefly", "Grand Prix", "GTO", "Lemans", "Parisienne", "Solstice", "Torrent", "Trans AM", "Vibe"],
  "Proton": ["AG", "Gen 2", "Persona", "Sega", "Waja", "Wira"],
  "Radical": ["SR1", "SR3", "SR8"],
  "Rally Fighter": ["IS3"],
  "Rariro": ["Classic"],
  "Rely": ["R8"],
  "Rivian": ["R1 S", "R1 T"],
  "SSangyong": ["Actyon", "Chairman", "CS", "G20D", "Korando", "Kyron", "Musso", "Pick up", "Rexton", "Tivoli", "Torres", "XLV"],
  "SWM": ["G01F", "G05 Pro"],
  "Saab": ["93", "95", "X97"],
  "Saturn": ["Sky"],
  "Scania": ["A80", "Standard"],
  "Seat": ["Al Hambra", "Cordoba", "Cubra", "EXEO", "Ibiza", "Leon", "Toledo"],
  "Skoda": ["Fabia", "Kamiq", "Karoq", "Kodiaq", "Kushaq", "Octavia", "Rapid", "Scala", "Superb", "Yeti"],
  "Smart": ["Brabus", "Carlsson", "Edition1", "ForTwo", "Lorinser", "MHD", "Passion", "Proxy", "Pure", "Roadster", "ultimate 125"],
  "Soueast": ["S06", "S07", "S09"],
  "Studebaker": ["Classic", "Gran Turismo"],
  "TAM": ["Vika"],
  "TATA": ["310", "Bus", "Pickup", "Xenon"],
  "TVR": ["Classic"],
  "Taxi london": ["LT"],
  "Today Sunshine": ["M1"],
  "Triumph": ["Spitfire"],
  "Vanderhall": ["Carmel", "Venice"],
  "Voyah": ["Dream", "Free"],
  "Wiseman": ["GT"],
  "Wuling": ["Hongguang.", "Mini EV"],
  "XPeng": ["G6", "G9", "P7"],
  "Xiaomi": ["SU7", "YU7"],
  "Yamaha": ["Buggy", "Rapter", "Rhino"],
  "YoYo": ["Standard"],
  "Zeekr": ["001", "7X", "9X", "X"],
  "Zheng Zhou": ["Rich"],
  "Zhongxing": ["Terralord"],
  "Zimmer": ["Golden Spirit"],
  "Zotye": ["E", "T"],
  "Zotye Domy": ["X5", "X7"],
  "Zxauto": ["Grand Lion", "Grand Tiger", "Terralord"],
  "daewoo": ["Lester"],
  "lucid": ["Grand Touring", "Pure", "Sapphire", "Touring"],
};

export const CAR_TRIMS: Record<string, string[]> = {
  "001": ["Long range", "Performance"],
  "01": ["Hyper", "Hyper Pro", "Louder Pro"],
  "03": ["+", "Hyper Plus", "Hyper Pro"],
  "05": ["Hyper Halo", "Hyper Plus"],
  "07": ["Max"],
  "09": ["Halo", "Pro", "Ultra"],
  "1-Series": ["118i", "120i", "125i", "128i", "135i", "138i", "140i M"],
  "12": ["GT"],
  "124": ["Spider"],
  "159": ["JTS"],
  "2": ["Stander"],
  "2-Series": ["218i", "220i", "225i", "228i", "235i"],
  "2002": ["Classic"],
  "2008": ["Allure", "GT Line"],
  "206": ["CC", "GT"],
  "207": ["RC", "RC Turbo", "cc"],
  "208": ["GT Line", "GTB"],
  "212": ["T01", "T01 Adventure Package"],
  "280": ["Classic"],
  "296": ["GTB", "GTS"],
  "3": ["Comfort"],
  "3-Series": ["315i", "316i", "318CI", "318i", "320", "320i", "320i GT", "323i", "325i", "328i", "330ci", "330i", "335", "335CI", "335i", "340i", "350ci"],
  "300 ZX": ["Turbo"],
  "3008": ["Active", "Allure", "GT Line"],
  "300C": ["SRT", "SRT8"],
  "301": ["Access"],
  "308": ["CC", "GT", "GT line", "RCZ"],
  "308 GTB": ["Turbo"],
  "328": ["GTS"],
  "355": ["GTS"],
  "356": ["Replica", "speedster"],
  "4-Series": ["420 I", "420 I M", "428 I", "428 I Gran Coupe", "430 I", "430 I M", "435 I", "435 I Individual", "440 I", "440 I M"],
  "408": ["GT"],
  "458": ["Italia", "Italia Spider", "Novitec Rosso", "Special", "Spider"],
  "488": ["Challenge Evo", "GTB", "GTB Hamann", "Novitec", "Pista", "Spider"],
  "4Runner": ["TRD Pro", "limited"],
  "5": ["Luxury"],
  "5-Series": ["520i", "520i M", "523i", "525", "525i", "528i", "530", "530i", "530i M", "535i", "535i GT", "540i", "540i M", "545i", "550i", "550i GT"],
  "500": ["Abarth", "Abarth 695 Rivale", "Dolcevita", "Gucci", "L", "Rockstar", "X"],
  "5008": ["Allure", "GT LINE"],
  "504": ["GL"],
  "508": ["GT line"],
  "512": ["BBi", "Testarossa 512 TR"],
  "540": ["C"],
  "570": ["F", "GT", "S"],
  "575": ["Maranello", "Super America"],
  "595": ["Abarth", "Abarth Competizione", "Abarth Scorpionero", "Esseesse"],
  "599": ["GTB"],
  "6-Series": ["630 Ci", "630i", "630i GT", "635i", "640i", "640i Gran Coupe", "645", "645 Ci", "650i", "650i Gran Coupe", "Alpina B6"],
  "600": ["LT"],
  "650 S": ["Spider"],
  "675 LT": ["Speed", "Spider MSO Carbon Series"],
  "695": ["Abarth", "Turismo"],
  "7": ["300", "405"],
  "7-Series": ["728 LI", "730 Li", "730 Li Individual", "735", "735 Li", "735 i", "740", "740 Li", "740 Li Individual", "740 Li M", "740 i", "740 iL", "740i M Sport", "745 Li", "750 IL", "750 LI Schnitzer", "750 Li", "750 Li Individual", "750 i", "760 Li", "760i"],
  "718": ["Spyder", "Spyder RS", "Spyder RS Weissach", "Spyer RS Sonderwunch"],
  "720": ["S"],
  "750": ["S"],
  "8": ["Super"],
  "8-Series": ["840 i", "840i Gran Coupe", "840i M Package", "850 ci", "850M", "850i"],
  "812": ["GTS", "Superfast", "Superfast GTS"],
  "85": ["+"],
  "911": ["992 Turbo S", "993 Turbo", "Backdate", "Carrera", "Carrera 4", "Carrera 4 Cabriolet", "Carrera 4S", "Carrera 4S Cabriolet", "Carrera 50", "Carrera Cabriolet", "Carrera GT", "Carrera GTS", "Carrera S", "Carrera S Cabriolet", "Carrera T", "Carrera Turbo", "Carrera Turbo 50 Years Edition", "Carrera Turbo S", "Dakar", "GT Street", "GT Street Rs", "GT2", "GT2 RS", "GT2 RS Weissach", "GT3", "GT3 Clubsport", "GT3 RS", "GT3 RS-Weissach Package", "GT3 Touring", "GT4", "Heritage", "Slant Nose", "Speedster Cabriolet", "Sport Classic", "Targa 4", "Targa 4 GTS", "Targa 4S", "Techart GT Street RS", "Turbo", "Turbo S", "Turbo S Cabriolet"],
  "918": ["Spyder", "Weissach Package"],
  "93": ["Turbo X"],
  "95": ["2.3 T"],
  "991": ["GT3 Touring"],
  "997": ["Carrera 4S", "GT2 Club Sport", "Turbo"],
  "A-Class": ["150 AMG", "200", "200 AMG", "250", "250 AMG", "250 Edition 1", "35 AMG", "45 AMG", "45 Edition 1", "45 S AMG"],
  "A1": ["1.4", "S-Line"],
  "A3": ["1.4", "1.8T", "30 TFSI", "35 TFSI", "S-Line"],
  "A4": ["1.8 T", "2.0 T", "3.0 T quattro", "S-line"],
  "A5": ["1.8", "2.0 T", "3.0 T", "3.2 Quattro", "4.5 TFSI S-Line", "40 TFSI", "45 TFSI", "50 TFSI", "50 TFSI S-Line", "S-Line"],
  "A6": ["2.0 T", "2.0 TFSI S- Line", "2.8", "2.8 Quattro", "3.0 S-Line", "3.2 S Line", "3.5 TFSI Quattro", "40 TFSI", "45 TFSI", "55 TFSI", "55 TFSI S-Line", "L"],
  "A7": ["2.8 S line", "3.0", "3.0 S line", "3.0 T-Quattro", "3.5 FSI quattro", "4.0 S Line", "40 TFSI", "40 TFSI Quattro", "45 TFSI Quattro", "50 TFSI quattro"],
  "A8": ["3.0", "4.0", "4.2", "50 TFSI", "6.3", "L", "L 55TFSI", "L 55TFSI Quattro", "S-line", "TFSI Quattro", "W12 Quattro"],
  "AERO": ["8"],
  "ATS": ["V"],
  "ATTO 3": ["Plus"],
  "Acadia": ["AT4", "Denali", "SLE", "SLT"],
  "Accent": ["1.6"],
  "Accord": ["Coupe", "Crosstour", "EXL", "Sport"],
  "Aion": ["Y"],
  "Alpina": ["B4 Biturbo Coupe", "B5", "B5 S", "B6 Biturbo", "B6 Biturbo Coupe", "B7"],
  "Altima": ["2.5 S", "2.5 SL", "2.5 SV", "3.5 SE", "3.5 SL", "3.5 SV", "Coupe", "S", "SR", "Turbo SV"],
  "Amarok": ["Canyon"],
  "Armada": ["LE", "Platinum", "SE"],
  "Arrizo 5": ["Luxury"],
  "Arrizo 6": ["Pro"],
  "Arrizo 8": ["Luxury"],
  "Aurion": ["Grande", "Touring"],
  "Avalanche": ["Black Diamond", "LT", "LTZ", "Z71"],
  "Avalon": ["Limited", "XL", "XLE"],
  "Avant RS4": ["4.2"],
  "Aventador": ["50th Anniversary", "Dragon Edition", "LP700-4", "LP750 SV", "LP760", "Pirelli Edition", "Roadster", "S", "S Roadster", "SV", "SV Spyder", "SVJ", "SVJ Roadster", "SVJ Spider", "Special", "Spyder"],
  "Aveo": ["LS"],
  "Aviator": ["Presidental"],
  "Azera": ["Grandeur"],
  "Azure": ["Mullliner"],
  "B-Class": ["150", "160", "170", "200", "250", "250 Electric", "63 S"],
  "B70": ["S"],
  "BJ40 PRO": ["\u064dStandard"],
  "BX": ["5", "7"],
  "Baleno": ["GL"],
  "Beetle": ["Turbo", "Turbo R"],
  "Bentayga": ["Azure", "Black Edition", "First Edition", "Mansory", "Mulliner", "S", "Speed"],
  "Blazer": ["LT Premium", "LTZ Premium", "RS"],
  "Boxster": ["718", "Black edition", "GTS", "S", "S Black Edition"],
  "Brabus": ["Turbo"],
  "Bronco": ["Badlands", "Big Bend", "First Edition", "Outer Banks", "Raptor", "Sport", "Wild Trak", "XLT"],
  "C 500": ["Sport"],
  "C 600": ["Classic"],
  "C-Class": ["180", "180 AMG", "200", "200 AMG", "220", "230", "240", "250", "250 AMG", "280", "300", "300 4Matic", "300 AMG", "350", "400", "43 AMG", "450", "63 AMG", "63 AMG Edition 1", "63 AMG S", "63 Edition 507", "C 63 Black Series", "C63 AMG Brabus"],
  "C-HR": ["HIBRID"],
  "C70": ["T5"],
  "CC": ["R - Line"],
  "CENTURY": ["LIMITED"],
  "CL": ["500", "500 AMG", "55 AMG", "550 AMG", "600", "63 AMG", "65 AMG", "750 Brabus"],
  "CLA": ["200", "250", "250 AMG", "35 AMG", "45 AMG", "45 S AMG", "450"],
  "CLC": ["200", "230", "63 AMG"],
  "CLE": ["200", "200 AMG", "53 AMG"],
  "CLK": ["200", "230", "240", "280", "300", "320", "350", "55", "55 AMG", "63 AMG Black Series", "Brabus 3.8S", "DTM"],
  "CLS": ["280", "350", "350 AMG", "400", "400 AMG", "450", "500", "500 AMG", "53 AMG", "55 AMG", "550", "63 AMG", "63 Brabus", "63 S AMG"],
  "CRV": ["DX", "EX", "EXL", "LX", "Touring"],
  "CRZ": ["Hybrid"],
  "CS": ["35", "35 Plus+", "75", "75 Plus", "85", "95"],
  "CT": ["200h"],
  "CT5": ["Premium Luxury", "V", "V BLACKWING"],
  "CT6": ["Premium", "platinum"],
  "CTS": ["4", "V-Supercharged"],
  "CX": ["3", "30", "5", "60", "7", "9", "90"],
  "California": ["T"],
  "California F1": ["T"],
  "Camaro": ["1 LT", "RS", "SS", "SS Hennessey", "Z/28", "ZL1"],
  "Camry": ["GL", "GLE", "GLI", "GLX", "Grandi", "Hybrid", "LE", "Limited", "RZ", "SE", "TRD", "Touring", "XSE"],
  "Can-am": ["800R", "Maverick 1000"],
  "Canyon": ["AT4 X"],
  "Caprice": ["LS", "LTZ", "Royal", "SS"],
  "Captiva": ["LS", "LT", "LTZ", "Premier"],
  "Capture": ["Tce"],
  "Carmel": ["Blackjack", "GTS"],
  "Carnival": ["3.5L GDI"],
  "Cayenne": ["Coupe", "E Hybrid", "Exclusive", "GTS", "GTS Coup\u00e9", "Magnum", "Platinum", "S", "S Coupe", "S Hybrid", "Turbo", "Turbo Coupe", "Turbo GT", "Turbo Gemballa", "Turbo S", "Turbo Techart", "Turbo mansory"],
  "Cayman": ["718", "718 GTS", "718 S", "GT", "GT4", "GT4 RS", "GTS", "S"],
  "Centennial": ["V 380", "VS500"],
  "Cerato": ["1.6 EX", "Koup"],
  "Challenger": ["GT", "Hellcat", "Hellcat Red Eye", "R/T", "R/T Plus", "R/T SHAKER", "R/T Scat Pack", "R/T Scat Pack Widebody", "RT Scate Pack Swinger", "Red Eye", "SRT", "SRT Demon", "SRT Hellcat Redeye Widebody", "SRT-8", "SXT Plus", "T/A", "hennessy", "red eye hennessey"],
  "Charger": ["Daytona", "GT", "Hellcat", "Hemi", "Magnum", "R/T Plus", "RT", "SRT", "SRT 8", "SXT", "Scat Pack", "Scat Pack Hemi", "Swinger"],
  "Cherokee": ["Limited", "Sport", "TrailHawk"],
  "Chevelle": ["SS"],
  "Cheyenne": ["c 10"],
  "Chiron": ["Sport 110"],
  "City": ["K-ZE"],
  "Civic": ["EXI", "LXI", "RS", "Race Car", "Sport", "Type R"],
  "Classic": ["442", "454", "K500"],
  "Clio": ["RS", "RS-Sport"],
  "Cobalt": ["LTZ"],
  "Cobra": ["AC", "Roadster Replica", "Shelby"],
  "Commander": ["Overland"],
  "Compass": ["Limited", "Limited S", "North Edition", "Trailhawk", "Upland", "longitude"],
  "Concorde": ["Limited"],
  "Continental": ["Cartier", "Flying Spur", "Flying Spur GT", "Flying Spur Skyline Collection", "GT", "GT First Edition", "GT Mulliner", "GT Onyx", "GT Speed", "GT V8S", "GT W12", "GT3 R", "GTC", "GTS", "Reserve", "Speed Flying Spur", "Supersport"],
  "Coolray": ["Sport Limited"],
  "Cooper": ["Clubman JCW", "Clubman S", "CountryMan", "CountryMan  S", "CountryMan JCW", "Coupe", "GP", "GP Fitout", "GP Limited Edtion", "JCW", "Paceman", "Paceman S", "Racer", "S", "S 60 Years", "SE", "Works", "goodwood"],
  "Corolla": ["Cross Hybrid", "GLI", "GR", "Hybrid", "LE", "XLI"],
  "Corvette": ["383 Stroker", "3LT Z51", "C1", "C3", "C4", "C5", "C6", "C6 60th Anniversary Edition", "C7", "C7 LT3", "C8", "C8 70th Anniversary Edition", "C8 LT2", "C8 LT3", "C8 Stingray", "C8 Z51", "C8 ZLT", "Grand Sport", "Holdings", "Z06 70th Edition", "Z25 Collectors Edition", "Z25 Grand Sport", "Z51", "ZO6", "ZO6 60th Anniversary Edition", "ZO6 Carbon 65", "ZR 25", "ZR1"],
  "Countach": ["25th Anniversary Edition"],
  "Coupe": ["20V Turbo"],
  "Crafter": ["TDI"],
  "Cressida": ["Grande"],
  "Creta": ["Deluxe"],
  "Crown": ["Hybrid"],
  "Cruze": ["LS", "LT", "LTZ"],
  "Cullinan": ["Black Badge", "Novitec", "Onyx", "Series II", "Urban"],
  "Custom Cab": ["350"],
  "CyberBeast": ["Foundation Series"],
  "Cybertruck": ["Beast", "Foundation Series"],
  "D-Max": ["GT"],
  "DB": ["11", "12", "7", "9", "S", "S Superleggera", "X", "X 707"],
  "DTS": ["Limousine"],
  "Dashing": ["Flag Ship", "Luxury", "V1", "V2", "V4", "V5"],
  "Dawn": ["Black Badge"],
  "Daytona": ["Shelby"],
  "Deepal": ["G318"],
  "Defender": ["110", "110 ADVENTURE", "110 Bond Edition", "110 Carpathian Edition", "110 HERITAGE", "110 HSE", "110 Kahn", "110 S", "110 S Urban", "110 SE", "110 SE Dynamic", "110 SV", "110 Urban Edition", "110 X", "110 X Carpathian Edition", "110 X Dynamic", "110 X Dynamic HSE", "110 X Dynamic SE", "110 X Edition", "130", "130 First Edition", "130 HSE", "130 X", "75th Limited Edition", "75th Limited Edition URBAN", "90", "90 007 Edition", "90 ADVENTURE", "90 Carpathian Edition", "90 Fire & Ice Edition", "90 First Edition", "90 HERITAGE", "90 HSE", "90 HSE 75th Heritage Edition", "90 Kahn Design", "90 Plumb", "90 SE", "90 SE Urban", "90 SV", "90 Special Vehicle", "90 X", "90 X Dynamic", "Avantador", "Expdeition Limited", "First Edition", "First Edition 110", "Octa", "S 300", "SVX", "SVX 60th Anniversary Special Edition", "Twisted", "Urban", "X Dynamic", "X Dynamic SE"],
  "Denza": ["B5", "B5 Flag Ship", "B8", "B8 Flag Ship", "D9", "N 9", "N 9 Flagship", "Z 9"],
  "Discovery": ["Sport", "Sport HSE", "Sport R Dynamic", "Sport SE", "Sport Turbo", "Turbo"],
  "Dream": ["Hybrid"],
  "Durango": ["Citadel", "GT", "LTD", "Limited", "RT", "SLT", "Sport"],
  "Duster": ["LE"],
  "E": ["200", "350", "450"],
  "E 70": ["Pro"],
  "E-Class": ["200", "200 AMG", "220", "230", "240", "250", "280", "300", "300 AMG", "320", "350", "350 AMG", "400", "400 AMG", "43", "45 Turbo AMG", "450", "500", "500 AMG", "500 Brabus", "53 AMG", "55 AMG", "550", "63 AMG", "63 S", "63S AMG"],
  "E-Pace": ["R Dynamic", "S", "SE"],
  "E-Tron": ["55 Quattro", "GT", "RS", "S-Line"],
  "E5": ["Plus"],
  "EQA": ["350"],
  "EQB": ["300", "350"],
  "EQC": ["350", "400"],
  "EQE": ["+350", "500", "S63"],
  "EQS": ["450", "53", "580"],
  "ES": ["250", "300", "300h", "330", "350", "350 F-Sport"],
  "EV": ["5", "6", "9"],
  "EX": ["30", "35", "37"],
  "Eado": ["Plus"],
  "Eclipse": ["Cross Highline"],
  "Eco Sport": ["SE", "Titanium", "Trend"],
  "Edge": ["Limited", "SE", "SEL", "Sport", "Titanium"],
  "Edition1": ["Turbo"],
  "El camino": ["SS"],
  "Elantra": ["N"],
  "Electra": ["225 Limited Park Avenue", "455"],
  "Element": ["EX-P"],
  "Eletre": ["R", "S"],
  "Elva": ["Roadster"],
  "Emeya": ["S"],
  "Emgrand": ["Luxury"],
  "Emira": ["1st Edition"],
  "Emkoo": ["GE", "GL", "GS"],
  "Empow": ["GE", "GL", "GS"],
  "Emzoom": ["GB", "GL", "GS", "R Style", "Sport"],
  "Envoy": ["Denali", "XL"],
  "Epica": ["LS", "LT"],
  "Equinox": ["LT"],
  "Ertiga": ["GLX"],
  "Escalade": ["600", "ESV", "EXT", "Limited", "Platinum", "Premium", "Premium Luxury ESV", "Premium Luxury Sport", "Sport", "Sport Platinum", "V ESV", "V Supercharged"],
  "Escort": ["Titanium", "Trend"],
  "Everest": ["Sport", "Titanium"],
  "Evoque": ["Autobiography", "Dynamic", "Dynamic HSE", "Dynamic plus", "First edition", "Prestige", "R Dynamic SE", "R-Dynamic"],
  "Evora": ["400", "410", "410 Sport", "GT 430", "S"],
  "Exige": ["350", "380", "410 Sport", "Sport 390 Final Edition"],
  "Exige S": ["350", "430 FINAL EDITION"],
  "Exlantis": ["ES"],
  "Expedition": ["Eddie Bauer", "King Ranch", "Limited", "Limited EL", "Platinum", "Timberline", "XLT"],
  "Explorer": ["Limited", "ST", "Sport", "Sport Truck", "XLT"],
  "F": ["100", "150", "150 Baja", "150 FX4", "150 King Ranch", "150 Lariat", "150 Lariat Black Edition", "150 Lightning", "150 Limited", "150 Platinum", "150 Raptor", "150 Roush Supercharger", "150 SVT", "150 Shelby", "150 Shelby Baja", "150 Shelby Super Snake", "150 Sport", "150 Tremor", "150 X Metal", "150 XLT", "150 harley davidson", "250", "250 King Ranch", "250 Super duty", "350", "350 Dual Rear Wheels", "350 Super duty", "450", "550", "650", "650 Super duty", "Black Ops"],
  "F-Pace": ["First Edition", "R Sport", "S", "SVR"],
  "F-Type": ["F portfolio", "S", "SVR", "Supercharged"],
  "F-Type R": ["SuperCharged"],
  "F12": ["Berlinetta"],
  "F2001 Formula 1": ["Michael Schumacher"],
  "F430": ["Scuderia"],
  "F8": ["Spider", "Tributo"],
  "F8 Tributo": ["Spider"],
  "FJ Cruiser": ["Final Edition", "TRD"],
  "FLEX": ["LTD", "Limited"],
  "FX": ["35", "37", "45", "50", "50S", "Vettel"],
  "Fairlady": ["Roadster"],
  "Fiorino": ["Cargo V"],
  "Firebird": ["Trans AM"],
  "Five Hundred": ["Limited", "SEL"],
  "Fleetwood": ["Brougham", "Limousine"],
  "Focus": ["RS", "ST", "Titanium"],
  "ForTwo": ["Mansory", "Proxy"],
  "Fortuner": ["SR5", "TRD"],
  "Free": ["318"],
  "Friday": ["EV"],
  "Fronx": ["GL", "GLX"],
  "Fusion": ["S", "Titanium"],
  "G": ["25", "35", "37", "37S", "37X"],
  "G-Class": ["230", "280", "280 GE", "300", "320", "350", "350 Professional Deisel", "350 d", "400", "400 Turbo", "400 d", "463 Edition", "500", "500 4X4", "500 4x4 Squared", "500 AMG", "500 AMG Night Pack", "500 Brabus", "500 Cabriolet", "500 Night Pack", "55 AMG", "55 AMG Arabia", "55 Brabus", "55 Haman", "550", "580 AMG", "63 AMG", "63 AMG  Urban", "63 AMG 4x4\u00b2", "63 AMG Edition 1", "63 AMG ONYX", "63 Brabus", "63 Diamond Edition", "63 Mansory", "63 Night Pack", "63 Night Pack AMG", "63 Stonger Than Time", "65 AMG", "700 Brabus", "800 Brabus", "AMG Stronger Than Time", "G63 6*6", "G63 AMG GRONOS 4x4", "Pick Up"],
  "G55": ["Super"],
  "G70": ["Royal Plus"],
  "G700": ["Comfort", "Flagship", "luxury"],
  "G9": ["performance"],
  "G90": ["Premium"],
  "GA6": ["GB", "GE", "GL"],
  "GA8": ["2.0T"],
  "GE": ["300"],
  "GL": ["450", "500", "55 AMG", "550", "63 AMG", "Brabus"],
  "GLA": ["200", "220", "250", "35", "45", "45 AMG", "45 AMG Edition 1", "45s AMG", "850 Brabus"],
  "GLB": ["200", "250", "250 AMG"],
  "GLC": ["200", "200 AMG", "250", "250 AMG", "300", "300 AMG", "410 Brabus", "43", "43 AMG", "63 S AMG"],
  "GLE": ["350", "400", "400 AMG", "43 AMG", "43 AMG Coupe", "450", "450 AMG", "500", "53 AMG", "53 AMG Coupe", "63S AMG", "63S AMG COUPE", "700 Brabus", "800 Brabus", "850"],
  "GLK": ["250", "280", "300", "350"],
  "GLS": ["400", "400 d", "450", "450 AMG", "500", "550", "580", "600 Maybach", "63 S AMG"],
  "GN": ["8"],
  "GN6": ["GE"],
  "GS": ["200 T", "250", "300", "350", "350 F Sport", "400", "430", "450 H", "460", "F Sport"],
  "GS 3": ["EMZOOM"],
  "GS8": ["GL", "GT", "GX", "Trumpchi"],
  "GT": ["40", "43 AMG", "53 AMG", "63 S AMG", "Black Series", "C 63 AMG", "C AMG", "C AMG Edition 50", "C Edition 1 of 500", "MF4", "R AMG", "S AMG", "S AMG Edition 1", "Speed", "Speed First Edition", "Sport", "SuperSports", "V8"],
  "GT 86": ["750 LI", "GR"],
  "GT-R": ["35", "35 Black Edition", "Black Edition", "Nismo", "Skyline"],
  "GTB": ["296", "488", "599"],
  "GTC": ["SPEED", "W12 Speed", "v8"],
  "GTX": ["1"],
  "GV 70": ["Royal Plus"],
  "GV 80": ["Coupe"],
  "GX": ["350", "460", "470", "550", "550 Luxury Plus", "550 Overtrail"],
  "GX 3": ["Pro"],
  "Gallardo": ["LP-500", "LP-550", "LP-560", "Limited Edition", "Spider", "Super Trofeo Stradale", "Valentino balbony"],
  "Gemballa": ["Avalanche"],
  "Genesis": ["5.0", "Coupe", "G70", "G80", "G90", "HTrac"],
  "Ghibli": ["GT", "Gran Lusso", "Q4", "S", "SQ4", "Trofeo"],
  "Ghost": ["Black Badge", "Brabus 700", "One Of One"],
  "Giulia": ["Quadrifoglio", "Veloce"],
  "Giulietta": ["Super"],
  "Gladiator": ["Launch Edition", "Mojave", "Overland", "Rubicon", "Sand Runner", "Sport"],
  "Glory": ["500", "600"],
  "Golf": ["GTI", "R", "R MK7", "R32", "TDI", "TSI"],
  "Gran Turismo": ["Hawk"],
  "GranTurismo": ["MC", "MC Sport Line", "Modena", "S", "Sport CC"],
  "Grancabrio": ["Fendi", "Sport"],
  "Grand Cherokee": ["75th Anniversary Edition", "Altitude", "Laredo", "Limited", "Limited Edition", "Limited L", "Overland", "S", "SRT", "SRT-8", "SRT-8 Supercharger", "Summit", "TrackHawk", "TrackHawk Hellcat", "trail hock"],
  "Grand Prix": ["GTP"],
  "Grand Wagoneer": ["Series 2", "Series 3"],
  "Granvia": ["premium"],
  "Grecale": ["GT", "Modena"],
  "Grenadier": ["Trialmaster"],
  "Groove": ["LT", "Premier"],
  "H1": ["Alpha", "LS3 Engine"],
  "H3": ["T", "V8"],
  "H5": ["35td", "40td", "45td"],
  "H6": ["Intelligent", "Supreme"],
  "H9": ["Comfort", "Super-Dignity"],
  "HHR": ["SS"],
  "HS": ["Sport"],
  "HS3": ["45 TD"],
  "HS7": ["ID50"],
  "Han 3.95": ["Ev-S"],
  "Hennessey": ["Venom 775"],
  "Hiace": ["GL"],
  "Highlander": ["Hybrid", "Limited"],
  "Hilux": ["GR Sport", "SR5", "SR5 Adventure", "TRD"],
  "Himava": ["Comfort", "Flagship", "Luxury"],
  "Holden": ["SS"],
  "Hongguang.": ["Mini EV"],
  "Hot Road": ["33"],
  "Hummer EV": ["Pickup", "SUV"],
  "Huracan": ["EVO", "LP-580", "LP610-4", "Performante", "STO", "Sterrato", "Tecnica"],
  "I": ["10", "30"],
  "I-Pace": ["90 HSE"],
  "I-Series": ["3", "4", "5", "7", "8", "i5 M60"],
  "ID": ["3", "3 Pro", "4", "4 Crozz Prime", "4 Pro", "4 Pro Crozz", "4 Pure Plus", "6", "6 Crozz", "6 Prime", "6 pure plus"],
  "IS": ["200t F", "250", "250 F Sport", "300", "300 C", "300 F", "350", "350 F", "350 F Black Edtion", "350 F Sport", "F"],
  "IX": ["1", "1 XDrive", "3", "40", "50", "M60"],
  "Impala": ["LS", "LTZ", "Premier", "SS"],
  "Impreza": ["2.0", "STI", "WRX"],
  "Ioniq": ["5"],
  "J7": ["Intelligent", "Luxury"],
  "JS3": ["Superb"],
  "JS4": ["Intelligent"],
  "JS6": ["Flagship", "Intelligent", "Luxury"],
  "JX": ["35"],
  "Jetta": ["S", "SE", "SEL"],
  "Jimmy": ["GL"],
  "Jimny": ["GL", "GLX"],
  "Jishi": ["01", "01 VIP", "Adamas black edition"],
  "Jolion": ["Pro"],
  "Juke": ["Nismo", "Turbo"],
  "K5": ["GT"],
  "KTM": ["X-Bow"],
  "Kicks": ["SL", "SR"],
  "Kodiak": ["C4500"],
  "Kona": ["N line"],
  "Kuga": ["SE"],
  "L 200": ["Diesel"],
  "LC": ["500", "500h"],
  "LFA": ["A"],
  "LM": ["350"],
  "LR2": ["HSE", "SE"],
  "LR3": ["HSE", "SE"],
  "LR4": ["HSE", "SE", "Supercharged"],
  "LS": ["350", "400", "430", "460", "460 L", "460 Sport", "470", "500", "500 H", "600 H", "600 HL", "760"],
  "LX": ["2.30 T", "450", "470", "540 d", "570", "570 Platinum", "570 S", "570 S Black Edition", "570 supercharger", "600", "600 F Sport", "600 Grandeur", "600 Luxury", "600 Overtrail", "600 Premium", "600 Ultra Luxury", "600 VIP", "600 VIP Black Edition", "700 h", "700h Overtrail", "Desel"],
  "Lancer": ["EX", "Evolution", "Evolution 6.5 Tommi Makinen", "Evolution MR", "Evolution-10", "Evolution-9", "FORTIS", "GLS", "GT"],
  "Land Cruiser": ["EXR", "G", "G Limited", "GR Sport Twin Turbo", "GX", "GX Limited", "GXR", "GXR - Limited", "GXR - TRD", "GXR Black Edition", "GXR Twin Turbo", "GXR White Edition", "GXR- Grand Touring", "Hard Top", "L200", "LX", "VX", "VX Twin Turbo", "VX.E", "VXR", "VXR - TRD", "VXR Black Edition", "VXR Limited", "VXR PLATINUM EDITION", "VXR Twin Turbo", "VXR White Edition", "VXR- Grand Touring S", "VXS", "VXS Black Edition", "VXS White Edition", "VXS- Grand Touring S", "X-Treme"],
  "Leon": ["Cobra", "FR", "TSI"],
  "Leopard 3": ["Titanium 3 Ultra"],
  "Leopard 5": ["Long Range", "Navigator", "Ultra 5", "Ultra Plus"],
  "Leopard 7": ["Titanium", "Titanium 7", "Ultra"],
  "Leopard 8": ["Flagship"],
  "Levante": ["Ermenegildo Zegna", "GT", "GTS", "Gran Lusso", "Modena", "Modena S", "Q4", "S", "SQ4", "Trofeo"],
  "Levin": ["GT", "Hybrid"],
  "Lumina": ["LTZ", "S", "SS"],
  "M": ["35", "37", "45", "500", "56S", "600"],
  "M-Series": ["1", "135 i", "2", "2 CS", "2 Competition", "235 i", "240i", "3", "3 CS", "3 Competition", "340 i", "4", "4 CS", "4 CSL", "4 Competition", "4 DTM Champion Edition", "4 GTS", "440i", "5", "5 30th Anniversary", "5 CS", "5 Competition", "5 First Edition", "5 Jahre Edition", "550i", "6", "6 Competition", "6 Gran Coupe", "650", "760 Li", "8", "8 Competition", "840 i", "850 i", "M4 Competition XDrive", "M5 Performance"],
  "M8": ["GL"],
  "M817": ["Hybrid", "Smart"],
  "MC Stradale": ["Limited", "line sport"],
  "MKX": ["RESERVE", "Select"],
  "ML": ["320", "350", "350 AMG", "400", "400 AMG", "420", "500", "500 AMG", "55 AMG", "550", "63 AMG", "63 Brabus"],
  "MX": ["5"],
  "Macan": ["GTS", "S", "Turbo"],
  "Mage": ["320 T"],
  "Magnum": ["SRT 8"],
  "Malibu": ["LS", "LT", "LTZ", "Turbo"],
  "Mark": ["LT"],
  "Maxima": ["S", "SR", "SV"],
  "Maybach": ["57 S", "GLS 600", "S500", "S560", "S580", "S600", "S650", "S680", "VS 680L"],
  "Mazda 3": ["Skyactiv G"],
  "Mazda 6": ["Ultra"],
  "Mazda Speed": ["MX5"],
  "Megane": ["GT Line", "RS"],
  "Model 3": ["Long Range", "Performance"],
  "Model S": ["100D", "Long Range", "Plaid"],
  "Model X": ["100 D", "Plaid"],
  "Model Y": ["Long Range", "Performance"],
  "Monjaro": ["Luxury"],
  "Mulsanne": ["Mulliner", "Sinjari Edition", "Speed", "W.O. Edition"],
  "Murano": ["LE", "Platinum", "SE", "SL"],
  "Murcielago": ["LP640", "SV"],
  "Mustang": ["Boss 302", "Boss 351", "Bullitt", "California", "Dark Horse", "Ecoboost", "Eleanor", "GT", "GT Premium", "GT-CS", "Mach-E", "Mach-E GT Performance", "Mach1 edition", "Mach1-390", "Roush", "Roush 427R", "SVO", "Saleen", "Shelby", "Shelby GT350", "Shelby GT500"],
  "NSX": ["R"],
  "NX": ["200 T", "200t F Sport", "300", "300 F Sport", "300 T", "350", "350 F Sport", "350 Luxury"],
  "Nautilus": ["Turbo 2.7"],
  "Navara": ["LE", "SE"],
  "Navigator": ["L", "Presidential"],
  "Neon": ["LX", "SXT"],
  "Nitro": ["RT", "SRT-10"],
  "Niva": ["Legend"],
  "Nomad": ["Super Charged"],
  "ORA 03": ["EV"],
  "Octavia": ["RS"],
  "Odyssey": ["Touring"],
  "Omoda": ["5 Luxury"],
  "One": ["Reve"],
  "One 77": ["Q"],
  "Optima": ["2.0", "2.4", "GT Line"],
  "Optiq": ["Luxury", "Premium Luxury", "Sport", "V-Series"],
  "Ousado": ["40 TD"],
  "Outlander": ["HL", "HL +", "Limited edition", "ML", "PL", "PL +"],
  "P1": ["GTR"],
  "P8": ["Deluxe"],
  "POER": ["Luxury", "Platinum", "Top"],
  "Pajero": ["3.0", "3.5", "3.8", "3.8 Gold Edition", "GLS", "Limited Edition", "Montero Sport", "Sport"],
  "Palisade": ["Calligraphy"],
  "Panamera": ["4", "4 Executive", "4S", "4S Executive", "4S LTD", "4S Middle east Edition", "E-Hybrid", "GTS", "Platinum Edition", "Premium Edition", "S", "S-Hybrid", "Turbo", "Turbo Executive", "Turbo S", "Turbo S  E-Hybrid"],
  "Passat": ["CC", "CC R Line", "R 36", "SE", "SEL", "Sport"],
  "Passion": ["42", "Edition 1", "Edition 1 Turbo"],
  "Pathfinder": ["Hybrid SV", "LE", "Platinum", "SE", "SL", "SV"],
  "Patrol": ["GL", "GL-V", "Gazelle Storm", "LE", "LE Platinum", "LE Titanium", "LE Turbo", "Nismo", "Pickup", "Platinum", "Platinum turbo", "Pro-4X", "SE", "SE Platinum", "SE T2", "SE Titanium", "SGL", "Safari", "Safari The Legend", "Super Safari", "Titanium", "Titanium Turbo", "VVIP Edition", "XE"],
  "Phantom": ["Chicane", "Coupe", "Drophead", "EWB", "Mansory", "Pininfarina", "Series II", "Water Speed LTD", "Zenith"],
  "Picanto": ["GT Line", "X-Line"],
  "Pick up": ["Tunland"],
  "Pickup": ["AK Series"],
  "Pilot": ["EX", "EXL", "Special Edition", "Touring"],
  "Poer": ["Elite", "Luxury", "Pilot"],
  "Portfolio": ["Supercharged"],
  "Power Wagon": ["6x6"],
  "Prado": ["First Edition", "GX", "GXL", "GXR", "TX Turbo", "TXL", "VX", "VXL", "VXR"],
  "Prius": ["Hybrid"],
  "Proxy": ["Cabrio"],
  "Q": ["30", "30S", "40", "45", "50", "50 S", "60", "60 S", "70", "70 S", "80"],
  "Q2": ["25 TFSI", "30 TFSI", "35 TFSI", "E-Tron"],
  "Q3": ["2.0 T", "3.0 TFSI", "35 TFSI", "4.0 Sline", "40 TFSI Quattro", "Quattro TFSI", "S Line"],
  "Q5": ["2.0 T", "2.0 T Quatro", "3.0 T", "3.0 T S-Line", "3.2 S-Line", "4.0 T", "40 TFSI Quattro", "40 TFSI S-Line", "45 TFSI", "45 TFSI Quattro", "45 TFSI Quattro S-Line", "Etron"],
  "Q6": ["E-tron"],
  "Q7": ["3.0", "35 TFSI Quattro", "40 TFSI", "42 Quattro", "45 TFSI Quattro", "45 TFSI Quattro S-line", "55 TFSI", "S-Line"],
  "Q8": ["55 TFSI Quattro", "E-Tron", "Prestige", "RS", "S-Line", "TFSI Quattro"],
  "QX": ["30", "4", "50", "50S", "55", "56", "60", "65", "70", "70 Limited", "70S", "80", "80 Autograph"],
  "Qashqai": ["LE", "SE"],
  "Qin Plus": ["DM-i", "EV"],
  "Quattroporte": ["330", "GTS", "Granlusso", "Q4", "S", "SQ4"],
  "R-Class": ["280", "300", "320", "350", "500"],
  "R107": ["SL380"],
  "R8": ["4.2 Coupe", "5.2 plus", "GT Spyder", "Quattro FSI", "RWS", "Spyder V10", "V10", "V10 Plus", "quattro spyder 5.2"],
  "RC": ["200T", "350", "350 F Sport", "F"],
  "RCZ": ["Turbo"],
  "RS": ["3", "4", "5", "5 Quattro TFSI", "6", "7", "E-tron GT", "Q 8", "Q3", "Q5"],
  "RSQ8": ["Performance"],
  "RSS": ["4.2 Coupe"],
  "RX": ["1", "2.0 T Flagship", "300", "330", "350", "350 Black edition", "350 F Sport", "350 L", "400T FlagShip", "450h", "500h F SPORT", "7", "8", "Turbo"],
  "RX5": ["Turbo"],
  "RX8": ["30 T"],
  "RX9": ["Luxury", "Premium"],
  "RZ-R": ["1000", "800", "900"],
  "Radar Rd 5": ["EV"],
  "Raize": ["GR"],
  "Ram": ["1200", "1500", "1500 Classic", "1500 Laramie", "1500 RHO", "1500 Sport", "2500", "2500 Power Wagon", "3500", "Big Horn", "Hemi Black edtion", "Laramie Longhorn", "Limited", "Power Wagon", "RT", "Rebel", "Rebel X", "SLT", "SRT", "SRT-10", "TRX", "TRX Final Edition", "TRX Ignition Edition", "TRX Lunar Edition", "TRX Sand Blast Edition", "Tungsten", "Warlock", "laramie", "longhorn", "viper"],
  "Range Rover": ["HSE", "SV", "SV Sadaf Edition", "Sport", "Sport -SuperCharged URBAN Edition", "Sport Autobiography", "Sport Dynamic", "Sport First Edition", "Sport HSE", "Sport HSE Dynamic", "Sport HSE Supercharged", "Sport HST", "Sport Overfinch", "Sport SE", "Sport SV", "Sport SVR", "Sport Super charged", "Sport Super charged HST", "Sport URBAN Edition", "VELAR HSE", "Velar", "Velar  S", "Velar - First Edition", "Velar Landmark Edition", "Velar R Dynamic HSE", "Velar R Dynamic Urban Edition", "Velar R-Dynamic", "Velar SE", "Velar SE R- Dynamic", "Velar SV", "Velar SV Autobiography", "Velar Urban Edition", "Vogue", "Vogue  Autobiography", "Vogue  Autobiography L", "Vogue  LSE", "Vogue Autobiography B.E", "Vogue Autobiography SV", "Vogue First Edition", "Vogue HSE", "Vogue HSE L", "Vogue SE", "Vogue SE L", "Vogue SE Super charged", "Vogue SE Super charged L", "Vogue SV", "Vogue SV Autobiography L", "Vogue SVR", "Vogue Super charged", "Vogue Super charged L", "Vogue URBAN Edition", "Vogue-SuperCharged URBAN Edition"],
  "Ranger": ["Raptor", "Wildtrak", "XLS", "XLT"],
  "Rapide": ["AMR", "S"],
  "Rapter": ["Performance"],
  "Raptor": ["2500 Super Duty", "Performance", "R", "Roche", "SVT", "SVT Limited Edition Hennessey", "Shelby", "Supercharger"],
  "Rav 4": ["HYBRID"],
  "Renegade": ["Limited", "Longitude", "Sport"],
  "Revo": ["R"],
  "Revuelto": ["LP1000-4"],
  "Riviera": ["455"],
  "Roadster": ["Replica"],
  "Rogue": ["SL", "Special Edition"],
  "Roma": ["Stradale"],
  "Routan": ["SE"],
  "Rover": ["1.3 i"],
  "Rush": ["S"],
  "S": ["3", "4", "40", "40 Turbo", "5", "6", "60", "60 Turbo", "7", "8", "8 Plus", "8 V8T", "80", "90"],
  "S-Class": ["230", "280", "300", "320", "350", "350 AMG", "350 L", "400", "400 AMG", "420", "450", "450 BRABUS", "450AMG", "500", "500 AMG", "500 Brabus", "500 Carlsson", "500 Edition 1", "55 AMG", "550", "550 AMG", "560", "560 Coupe", "580", "580 Brabus", "600", "600 AMG", "63 4Matic", "63 AMG", "63 AMG Edition 1", "63 AMG Edition 130", "63 brabus", "65 AMG", "65 Brabus", "650", "Edition 1"],
  "S-Type R": ["Supercharged"],
  "S5": ["GT", "Luxury"],
  "S50": ["Luxury"],
  "SC": ["430"],
  "SF90 Stradale": ["Assetto Fiorano", "Tailor Made"],
  "SL": ["190", "280", "320", "350", "380", "400", "43 AMG", "450", "500", "500 AMG", "53", "55 AMG", "550", "560", "60 AMG", "63 AMG", "65 AMG"],
  "SLC": ["200", "300", "43", "450"],
  "SLK": ["200", "230", "250", "280", "300", "320", "350", "350 AMG", "55 AMG", "63 AMG"],
  "SLR": ["722", "Brabus", "Fab Design", "Haman", "Mansoory", "McLaren", "McLaren 722 Edition"],
  "SLS": ["500", "63 AMG", "Black Series", "Brabus", "FAB Design", "GT", "GTS", "Hamann", "Roadster"],
  "SR3": ["XX"],
  "SRX": ["4"],
  "SS": ["454"],
  "STS": ["V-Supercharger"],
  "SU7": ["Max", "Ultra"],
  "Santa Fe": ["Calligraphy", "Premium"],
  "Savana": ["Explorer Limited SE"],
  "Scion": ["FR-S", "I 10"],
  "Scirocco": ["R", "Turbo"],
  "Seal": ["7"],
  "Sealion": ["05", "06", "07"],
  "Seltos": ["EX", "GT Line"],
  "Senna": ["Limited Edition"],
  "Senova": ["J40", "J40L", "X35", "X65"],
  "Sequoia": ["Capstone", "Limited", "Platinum", "SR5", "TRD Pro", "TRD Sport"],
  "Shark": ["6"],
  "Shelby": ["Cobra MKIII Superformance", "GT 500", "Super Charged"],
  "Shine": ["GS", "Max", "Turbo"],
  "Shuailing": ["T6"],
  "Sian": ["FKP 37", "Roadster"],
  "Sienna": ["SE"],
  "Sierra": ["1500", "1500 Harley Davidson", "2500 HD", "3500", "3500 HD", "454", "AT4", "AT4 Carbon Pro", "AT4 X", "All Terrain", "Classic", "Denali", "Denali Supercharged", "Denali Ultimate", "Elevation", "SLE", "SLT", "Shaheen", "Ultimate", "Z71", "ZZ4"],
  "Silverado": ["2500 HD", "3100", "3500 HD", "454", "8100", "EV", "High Country", "LT", "LT Trail Boss Z71", "LTZ", "LTZ - Z71", "PaxPower Jackal", "RST", "Reaper", "SS", "Trail Boss", "Z71", "ZR 2"],
  "Skyline": ["GT-R", "R34 GT-R"],
  "SlingShot": ["R"],
  "Solara": ["SE"],
  "Sonata": ["N Line"],
  "Sorento": ["3.5"],
  "Soul": ["2.0", "Limited Edition"],
  "Spider": ["VELOCE"],
  "Sport": ["First edition"],
  "Sportage": ["1.5 Turbo", "1.6", "2.0", "2.0 EX", "2.4 LX", "GDI", "GT", "GT Line"],
  "Sprinter": ["VIP"],
  "Stelvio": ["Quadrifoglio"],
  "Stinger": ["GT"],
  "Suburban": ["LS", "LT", "LTZ", "Premier"],
  "Super Duty": ["250"],
  "Supra": ["A 91", "GR", "MKIV"],
  "T": ["300", "500", "600", "700"],
  "T-Roc": ["R Line", "Style"],
  "T1": ["Comfort", "Luxury", "Royal Edition"],
  "T2": ["C-DM", "Hybrid", "I-DM", "Luxury", "Luxury Plus"],
  "T33": ["Premium"],
  "T5": ["EVO", "Evo"],
  "T70": ["Pro"],
  "T99": ["Limousine", "Premium"],
  "TRUMPCHI": ["M8"],
  "TT": ["2.0", "45 TFSI", "Quattro", "RS", "S", "S-Line", "TFSI"],
  "TXL": ["Flagship"],
  "Tacoma": ["TRD Pro"],
  "Tahoe": ["High Country", "LS", "LS 4*4", "LT", "LT Premium", "LTZ", "Premier", "RST", "Z71"],
  "Tang": ["L"],
  "Tank": ["300", "400 Hi4-T", "500", "500 Black Edition", "700"],
  "Targa": ["4", "4S"],
  "Tasman": ["X PRO"],
  "Taurus": ["Limited", "SE", "SEL", "SHO", "Titanum", "Trend"],
  "Taycan": ["4 Cross Turismo", "4 S", "4 Sport Turismo", "GTS", "Turbo", "Turbo S"],
  "Telluride": ["EX", "GT Line"],
  "Teramont": ["Comfortline", "Highline", "R Line", "S", "SE", "SEL"],
  "Terrain": ["AT4", "Denali", "SLE", "SLT"],
  "Terralord": ["AT ESC"],
  "Territory": ["Platinum", "Titanium", "Trendline"],
  "Tiggo": ["2 Pro", "2 Pro Max", "3", "4 Pro", "7", "7 Pro", "7 Pro Max", "8 Pro Max", "8 Pro e+", "8 pro", "8 pro plus+", "9 pro", "9 pro flagship", "9 pro luxury", "9 pro max"],
  "Tiguan": ["1.4 TSI", "2.0 TSI", "9 pro max", "Elegance", "R-Line"],
  "Titan": ["XD"],
  "Touareg": ["Comfort Line", "Elegance Premium", "Highline plus", "Limited Black Edition", "R line", "Sport"],
  "Town Car": ["Cartier"],
  "TrailBlazer": ["LS", "LT", "LTZ", "LTZ   z71", "RS", "Z71"],
  "Traverse": ["LS", "LT", "LTZ"],
  "Trax": ["LS", "LT", "LTZ", "Premier"],
  "Tucson": ["Deluxe", "HTRAC", "LX 35", "Limited", "N Line"],
  "Tugella": ["Black Edition", "GF+", "GL", "Sport"],
  "Tundra": ["Capstone i-Force max", "Edition 1794", "Limited", "Platinum", "Rock Warrior", "SR5", "SRS", "Super Charger", "TRD", "TRD PRO", "TRD Sport", "TSS"],
  "Type 62": ["S"],
  "UX": ["200", "200 F Sport", "300 H"],
  "Unimog": ["1700 L", "U 1150", "U 500"],
  "Universe Space": ["Luxury"],
  "Urus": ["Graphite Capsule", "Mansory", "Novitec Esteso", "Performante", "S", "SE"],
  "Urvan": ["NV350"],
  "V": ["40", "50", "60", "70"],
  "V-Class": ["220", "250", "250 BlueTec", "250 Maybach", "250 VIP Brabus"],
  "V7": ["Premium"],
  "VX": ["400", "400 T"],
  "Vanquish": ["6.0", "Q edition", "S", "Zagato"],
  "Vantage": ["AMR", "GT 12", "N 430", "Roadster", "S", "Superleggera", "V12"],
  "Veloster": ["N", "Turbo"],
  "Venice": ["GTS"],
  "Venue": ["Premium"],
  "Veyron": ["Sang Noir"],
  "Viano": ["VIP Special Edition"],
  "View": ["C2", "CS2"],
  "Vika": ["T2"],
  "Viper": ["ACR", "GTS", "GTS-R", "SRT", "SRT-10", "TA"],
  "Vistiq": ["Luxury", "Premium Luxury", "Sport", "V-Series"],
  "WRX": ["STI"],
  "Wingle 5": ["Luxury"],
  "Wingle 7": ["Luxury"],
  "Wraith": ["Ares Edition", "Bespoke", "Black Badge", "Eagle eight", "Inspired By Music", "Sport"],
  "Wrangler": ["392", "392 Rubicon", "80th Anniversary", "CJ-7", "Night Eagle", "Rubicon", "Rubicon X", "SRT-8", "Sahara", "Sport", "Sport Plus", "Starwood", "Trail Rated", "Unlimited", "Willys"],
  "X-Class": ["220 d", "250 d", "350 EXY Extreme", "350 d", "55"],
  "X-Series": ["X M", "X1", "X1 M", "X2", "X2 M", "X3", "X3 30i", "X3 Competition", "X3 M", "X4", "X4 30i", "X4 40i", "X4 M", "X4 M Competition", "X5", "X5 40i", "X5 50i", "X5 M", "X5 M Competition", "X5 M40i", "X5 M50i", "X5 M60i", "X6", "X6 40i", "X6 50i", "X6 M", "X6 M Competition", "X6 M Edition black fire", "X6 M40i", "X6 M50i", "X6 M60i", "X7", "X7 40i", "X7 50i", "X7 M", "X7 M40i", "X7 M50i", "X7 M60i"],
  "X-Trail": ["SL", "SV"],
  "X3": ["Flagship", "Flagship PRO", "Luxury"],
  "X7": ["X7 40i"],
  "X70": ["Comfort", "FL", "Plus", "Plus Luxury"],
  "X90": ["Plus"],
  "XC": ["40", "60", "70", "90", "Polestar"],
  "XE": ["Prestige", "R Dynamic", "R Sport", "S"],
  "XF": ["R Supercharged", "R-Sport", "S", "V6 Supercharged", "V8", "i4 Turbo"],
  "XJ": ["12", "6", "8", "L", "L portfolio", "L premium luxury", "R", "R Supercharger", "S", "SuperSport"],
  "XJL": ["portfolio", "premium luxury"],
  "XK": ["8"],
  "XKR": ["S"],
  "XLR": ["V"],
  "XM": ["Label"],
  "XT4": ["Premium", "Premium Luxury"],
  "XT5": ["400", "Platinum", "Premium luxury", "Sport", "Trim"],
  "XT6": ["400 Platinum", "400 Premium Luxury"],
  "XTS": ["4"],
  "Xenon": ["GLE"],
  "Xpander": ["Cross"],
  "Xterra": ["Off Road", "Platinum", "S", "SE", "Titanium"],
  "YU7": ["Base", "Max"],
  "Yaris": ["GR"],
  "Yuagwang": ["U8"],
  "Yukon": ["AT 4", "Denali", "Denali XL", "Elevation", "SLE", "SLT", "XL", "XL SLT"],
  "Z": ["240", "240 ZX", "260", "280 ZX", "300", "300 ZX", "300 ZX Turbo", "34", "350", "370", "370 Nismo", "400", "ZX"],
  "Z-Series": ["3", "4", "4 20i", "4 M", "4 M40i", "8"],
  "ZR-V": ["EX", "EX SPORT", "LX"],
  "iCAR": ["EQ3", "EQ7", "O3 T", "V 23", "V27"],
  "ix": ["35"],
  "scuderia": ["430"],
  "ultimate 125": ["Brabus"],
  "yang Wang": ["U8"],
};

export const YEARS = Array.from({ length: 26 }, (_, i) => 2025 - i);

/** Minimum model year shown in the main car browse results (older = classic section) */
export const MIN_LISTING_YEAR = 2005;

/** Keywords in make/class_name/body_type that indicate a non-car listing */
export const EXCLUDED_NON_CAR_KEYWORDS = [
  'bike', 'bicycle', 'motorcycle', 'motorbike', 'moped', 'scooter',
  'jet ski', 'jetski', 'watercraft', 'pwc', 'seadoo', 'sea-doo',
  'atv', 'quad', 'quadbike', 'buggy', 'side by side', 'sxs', 'utv',
  'boat', 'yacht', 'speedboat', 'pontoon',
  'trike', 'three-wheel',
  'snowmobile', 'dirt bike', 'dirtbike',
];

/** Makes that are exclusively or primarily non-car brands in this market */
export const NON_CAR_MAKES = [
  'sea-doo', 'seadoo', 'yamaha watercraft', 'kawasaki (bikes)',
  'polaris', 'can-am', 'brp', 'arctic cat',
  'harley-davidson', 'harley davidson', 'ducati', 'ktm', 'triumph motorcycles',
  'royal enfield', 'bajaj', 'tvs',
];

/** Budget bands for the quick-select affordability chips */
export const BUDGET_BANDS = [
  { label: 'Under 50k',   value: 'under_50k',   max: 50_000,   min: 0 },
  { label: '50–100k',     value: '50_100k',      max: 100_000,  min: 50_000 },
  { label: '100–200k',    value: '100_200k',     max: 200_000,  min: 100_000 },
  { label: '200–400k',    value: '200_400k',     max: 400_000,  min: 200_000 },
  { label: '400k+',       value: 'above_400k',   max: undefined, min: 400_000 },
] as const;
export type BudgetBand = typeof BUDGET_BANDS[number]['value'] | 'any';

export const CONDITIONS = [
  { value: 'excellent', label: 'Excellent', description: 'Like new, no issues' },
  { value: 'good', label: 'Good', description: 'Minor wear, well maintained' },
  { value: 'fair', label: 'Fair', description: 'Some wear, needs minor repairs' },
  { value: 'poor', label: 'Poor', description: 'Significant issues or damage' },
];

export const QATAR_CITIES = [
  'Doha', 'Al Wakrah', 'Al Rayyan', 'Lusail', 'Al Khor', 'Al Shamal',
  'Al Daayen', 'Umm Slal', 'Madinat ash Shamal', 'Dukhan',
];

export const FUEL_TYPES = ['Petrol', 'Diesel', 'Hybrid', 'Electric'];
export const GEAR_TYPES = ['Automatic', 'Manual'];
export const CAR_TYPES = ['Sedan', 'SUV', 'Pickup', 'Hatchback', 'Coupe', 'Van', 'Convertible', 'Wagon'];
export const WARRANTY_STATUSES = ['Under Warranty', 'No Warranty', 'Extended Warranty'];
export const CYLINDER_OPTIONS = [4, 6, 8] as const;
export const SELLER_TYPES = ['private', 'dealer'] as const;

/**
 * Known model defaults for Qatar market vehicles.
 * When a model has fixed attributes (e.g. Land Cruiser is always SUV/Petrol/Automatic),
 * those fields are auto-filled and hidden from the form to reduce unnecessary input.
 * Only include fields that are truly fixed — leave out fields that vary across trims.
 */
export interface ModelDefaults {
  fuel_type?: string;
  gear_type?: string;
  car_type?: string;
}

export const MODEL_DEFAULTS: Record<string, ModelDefaults> = {
  // Toyota
  'Land Cruiser':       { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'SUV' },
  'Land Cruiser Prado': { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'SUV' },
  'Prado':              { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'SUV' },
  'Fortuner':           { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'SUV' },
  'Sequoia':            { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'SUV' },
  'Tundra':             { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'Pickup' },
  'Hilux':              { car_type: 'Pickup' },
  'Camry':              { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'Sedan' },
  'Corolla':            { fuel_type: 'Petrol', car_type: 'Sedan' },
  'RAV4':               { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'SUV' },
  'Rush':               { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'SUV' },
  'Yaris':              { fuel_type: 'Petrol', car_type: 'Sedan' },
  'Avanza':             { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'Van' },
  // Lexus
  'LX':                 { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'SUV' },
  'GX':                 { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'SUV' },
  'RX':                 { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'SUV' },
  'ES':                 { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'Sedan' },
  'LS':                 { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'Sedan' },
  'NX':                 { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'SUV' },
  // Nissan
  'Patrol':             { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'SUV' },
  'Patrol Safari':      { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'SUV' },
  'Altima':             { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'Sedan' },
  'Maxima':             { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'Sedan' },
  'Sentra':             { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'Sedan' },
  'X-Trail':            { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'SUV' },
  'Pathfinder':         { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'SUV' },
  'Kicks':              { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'SUV' },
  'Navara':             { car_type: 'Pickup' },
  // Infiniti
  'QX80':               { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'SUV' },
  'QX60':               { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'SUV' },
  'QX50':               { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'SUV' },
  'Q50':                { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'Sedan' },
  'Q70':                { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'Sedan' },
  // GMC
  'Yukon':              { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'SUV' },
  'Tahoe':              { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'SUV' },
  'Suburban':           { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'SUV' },
  'Acadia':             { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'SUV' },
  'Sierra':             { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'Pickup' },
  'Canyon':             { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'Pickup' },
  // Chevrolet
  'Silverado':          { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'Pickup' },
  'Traverse':           { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'SUV' },
  'Blazer':             { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'SUV' },
  'Captiva':            { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'SUV' },
  'Equinox':            { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'SUV' },
  'Malibu':             { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'Sedan' },
  'Camaro':             { fuel_type: 'Petrol', car_type: 'Coupe' },
  // Ford
  'F-150':              { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'Pickup' },
  'Explorer':           { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'SUV' },
  'Expedition':         { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'SUV' },
  'Ranger':             { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'Pickup' },
  'Edge':               { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'SUV' },
  'Mustang':            { fuel_type: 'Petrol', car_type: 'Coupe' },
  // Dodge
  'Durango':            { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'SUV' },
  'Charger':            { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'Sedan' },
  'Challenger':         { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'Coupe' },
  'Ram 1500':           { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'Pickup' },
  // Jeep
  'Grand Cherokee':     { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'SUV' },
  'Wrangler':           { fuel_type: 'Petrol', car_type: 'SUV' },
  'Cherokee':           { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'SUV' },
  'Gladiator':          { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'Pickup' },
  // BMW
  'X5':                 { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'SUV' },
  'X6':                 { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'SUV' },
  'X7':                 { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'SUV' },
  'X3':                 { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'SUV' },
  '5 Series':           { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'Sedan' },
  '7 Series':           { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'Sedan' },
  '3 Series':           { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'Sedan' },
  // Mercedes-Benz
  'G-Class':            { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'SUV' },
  'GLE':                { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'SUV' },
  'GLS':                { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'SUV' },
  'GLC':                { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'SUV' },
  'S-Class':            { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'Sedan' },
  'E-Class':            { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'Sedan' },
  'C-Class':            { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'Sedan' },
  // Land Rover
  'Range Rover':        { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'SUV' },
  'Range Rover Sport':  { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'SUV' },
  'Defender':           { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'SUV' },
  'Discovery':          { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'SUV' },
  // Audi
  'Q7':                 { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'SUV' },
  'Q8':                 { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'SUV' },
  'Q5':                 { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'SUV' },
  'A6':                 { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'Sedan' },
  'A8':                 { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'Sedan' },
  // Porsche
  'Cayenne':            { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'SUV' },
  'Macan':              { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'SUV' },
  'Panamera':           { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'Sedan' },
  // Hyundai
  'Palisade':           { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'SUV' },
  'Santa Fe':           { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'SUV' },
  'Tucson':             { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'SUV' },
  'Sonata':             { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'Sedan' },
  'Elantra':            { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'Sedan' },
  // Kia
  'Telluride':          { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'SUV' },
  'Sorento':            { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'SUV' },
  'Sportage':           { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'SUV' },
  'Carnival':           { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'Van' },
  // Honda
  'Pilot':              { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'SUV' },
  'CR-V':               { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'SUV' },
  'Accord':             { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'Sedan' },
  'Civic':              { fuel_type: 'Petrol', car_type: 'Sedan' },
  // Mitsubishi
  'Pajero':             { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'SUV' },
  'L200':               { car_type: 'Pickup' },
  'Eclipse Cross':      { fuel_type: 'Petrol', gear_type: 'Automatic', car_type: 'SUV' },
};

